services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Th1s1sS3cureP@ssword!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=Th1s1sS3cureP@ssword!
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  chart-service:
    build:
      context: ./src/chart-service
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=Th1s1sS3cureP@ssword!
      - MINIO_BUCKET=data-agent-reports
    depends_on:
      - minio

volumes:
  sqlserver_data:
  minio_data:
  n8n_data:
